# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DeUYhtlOuHwB1J84D3555FIkgUuJ3Hcj
"""



# task1.py
# TrendPulse - Task 1
# Goal: Fetch top trending posts from HackerNews API and save as JSON

import requests   # to make web requests
import json       # to save data as JSON file
import time       # to add small delay between requests (good practice)

# --- Step 1: Fetch the list of top story IDs ---

print("Fetching top story IDs from HackerNews...")

ids_url = "https://hacker-news.firebaseio.com/v0/topstories.json"
response = requests.get(ids_url)

# Check if request worked
print("Status Code:", response.status_code)

top_ids = response.json()          # this gives a list of IDs like [1234, 5678, ...]
top_ids = top_ids[:25]             # we only want top 25 posts

print(f"Got {len(top_ids)} story IDs")

# --- Step 2: Fetch details for each story ---

print("Fetching details for each story...")

posts = []   # empty list to collect all post data

for story_id in top_ids:
    # Build URL for each individual story
    story_url = f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json"

    story_response = requests.get(story_url)
    story = story_response.json()   # get that story's data

    # Some stories might be missing fields, use .get() to avoid errors
    extracted = {
        "id":          story.get("id"),
        "title":       story.get("title"),
        "author":      story.get("by"),
        "score":       story.get("score"),
        "num_comments": story.get("descendants", 0),  # 0 if no comments
        "url":         story.get("url", "No URL"),
        "time":        story.get("time")               # Unix timestamp
    }

    posts.append(extracted)
    print(f"  ✅ Fetched: {story.get('title', 'No title')[:50]}")  # print first 50 chars

    time.sleep(0.1)   # small pause so we don't spam the API

# --- Step 3: Save as JSON file ---

with open("hackernews_trending.json", "w") as f:
    json.dump(posts, f, indent=4)   # indent=4 makes it human-readable

print(f"\n✅ Done! Saved {len(posts)} posts to hackernews_trending.json")



# task2.py
# TrendPulse - Task 2
# Goal: Load JSON from Task 1, clean it using Pandas, save as CSV

import pandas as pd   # pandas for data cleaning
import json           # to read the JSON file

# --- Step 1: Load the JSON file into a DataFrame ---

with open("hackernews_trending.json", "r") as f:
    data = json.load(f)   # loads JSON as a Python list

df = pd.DataFrame(data)   # converts list of dicts into a table

print("=== Raw Data ===")
print(df)                 # see the full table
print("\nShape:", df.shape)  # (rows, columns)

# --- Step 2: Check for missing values ---

print("\n=== Missing Values ===")
print(df.isnull().sum())   # counts missing values per column

# Fill missing values
df['url'] = df['url'].fillna('No URL')          # if url is missing, fill with 'No URL'
df['author'] = df['author'].fillna('Unknown')   # if author missing, fill with 'Unknown'
df['score'] = df['score'].fillna(0)             # if score missing, fill with 0
df['num_comments'] = df['num_comments'].fillna(0)

# --- Step 3: Remove duplicate rows ---

print("\nDuplicates before:", df.duplicated().sum())
df = df.drop_duplicates()   # removes any repeated rows
print("Duplicates after:", df.duplicated().sum())

# --- Step 4: Convert Unix timestamp to readable date ---

# 'time' column has numbers like 1743600000 (seconds since 1970)
# We convert it to something like "2026-04-01 10:30:00"

df['time'] = pd.to_datetime(df['time'], unit='s')
print("\nSample date after conversion:", df['time'][0])

# --- Step 5: Remove posts with score = 0 ---

print("\nRows before score filter:", len(df))
df = df[df['score'] > 0]   # keep only rows where score is more than 0
print("Rows after score filter:", len(df))

# --- Step 6: Reset index ---

df = df.reset_index(drop=True)   # resets row numbers to 0,1,2,3...

# --- Step 7: Final check and save as CSV ---

print("\n=== Cleaned Data ===")
print(df.head())              # shows first 5 rows
print("\nData types:")
print(df.dtypes)              # shows type of each column

df.to_csv("hackernews_clean.csv", index=False)   # save, index=False means don't save row numbers

print("\n✅ Saved cleaned data to hackernews_clean.csv")

# task3.py
# TrendPulse - Task 3
# Goal: Analyse the cleaned CSV using NumPy and Pandas

import pandas as pd
import numpy as np

# --- Step 1: Load the cleaned CSV ---

df = pd.read_csv("hackernews_clean.csv")

print("=== Data Loaded ===")
print(df.head())           # first 5 rows
print("\nShape:", df.shape)  # rows and columns

# --- Step 2: Basic statistics using NumPy ---

scores = df['score'].values        # convert column to NumPy array
comments = df['num_comments'].values

print("\n=== Score Statistics ===")
print("Mean score:  ", round(np.mean(scores), 2))      # average
print("Median score:", round(np.median(scores), 2))    # middle value
print("Max score:   ", np.max(scores))                 # highest
print("Min score:   ", np.min(scores))                 # lowest
print("Std Dev:     ", round(np.std(scores), 2))       # how spread out scores are

print("\n=== Comment Statistics ===")
print("Mean comments:  ", round(np.mean(comments), 2))
print("Median comments:", round(np.median(comments), 2))
print("Max comments:   ", np.max(comments))
print("Min comments:   ", np.min(comments))

# --- Step 3: Highest scored post ---

top_post = df[df['score'] == df['score'].max()]
print("\n=== Highest Scored Post ===")
print("Title:", top_post['title'].values[0])
print("Score:", top_post['score'].values[0])
print("Author:", top_post['author'].values[0])

# --- Step 4: Most active author ---

top_author = df['author'].value_counts().idxmax()  # author with most posts
print("\n=== Most Active Author ===")
print("Author:", top_author)
print("Posts:", df['author'].value_counts().max())

# --- Step 5: Most commented post ---

top_comment = df[df['num_comments'] == df['num_comments'].max()]
print("\n=== Most Commented Post ===")
print("Title:", top_comment['title'].values[0])
print("Comments:", top_comment['num_comments'].values[0])

# --- Step 6: Score distribution ---

# Split scores into ranges: 0-100, 100-300, 300-600, 600+
bins = [0, 100, 300, 600, float('inf')]
labels = ['Low (0-100)', 'Medium (100-300)', 'High (300-600)', 'Viral (600+)']

df['score_category'] = pd.cut(df['score'], bins=bins, labels=labels)

print("\n=== Score Distribution ===")
print(df['score_category'].value_counts())

# --- Step 7: Correlation between score and comments ---

correlation = np.corrcoef(scores, comments)[0][1]
print("\n=== Correlation: Score vs Comments ===")
print(f"Correlation value: {round(correlation, 2)}")
print("(1.0 = perfect match, 0 = no relation, -1 = opposite)")

# --- Step 8: Save analysis summary as CSV ---

summary = pd.DataFrame({
    'metric': ['mean_score', 'median_score', 'max_score', 'min_score',
               'mean_comments', 'max_comments', 'score_comment_correlation'],
    'value': [round(np.mean(scores), 2), round(np.median(scores), 2),
              np.max(scores), np.min(scores),
              round(np.mean(comments), 2), np.max(comments),
              round(correlation, 2)]
})

summary.to_csv("hackernews_analysis.csv", index=False)
print("\n✅ Saved analysis to hackernews_analysis.csv")

from google.colab import files
files.download("hackernews_analysis.csv")