# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1074BSGIieE_zk63LjV-IzIAfwk5Iy0a8
"""

!pip install requests

# task1.py
# TrendPulse - Task 1
# Goal: Fetch top trending posts from HackerNews API and save as JSON

import requests   # to make web requests
import json       # to save data as JSON file
import time       # to add small delay between requests (good practice)

# --- Step 1: Fetch the list of top story IDs ---

print("Fetching top story IDs from HackerNews...")

ids_url = "https://hacker-news.firebaseio.com/v0/topstories.json"
response = requests.get(ids_url)

# Check if request worked
print("Status Code:", response.status_code)

top_ids = response.json()          # this gives a list of IDs like [1234, 5678, ...]
top_ids = top_ids[:25]             # we only want top 25 posts

print(f"Got {len(top_ids)} story IDs")

# --- Step 2: Fetch details for each story ---

print("Fetching details for each story...")

posts = []   # empty list to collect all post data

for story_id in top_ids:
    # Build URL for each individual story
    story_url = f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json"

    story_response = requests.get(story_url)
    story = story_response.json()   # get that story's data

    # Some stories might be missing fields, use .get() to avoid errors
    extracted = {
        "id":          story.get("id"),
        "title":       story.get("title"),
        "author":      story.get("by"),
        "score":       story.get("score"),
        "num_comments": story.get("descendants", 0),  # 0 if no comments
        "url":         story.get("url", "No URL"),
        "time":        story.get("time")               # Unix timestamp
    }

    posts.append(extracted)
    print(f"  ✅ Fetched: {story.get('title', 'No title')[:50]}")  # print first 50 chars

    time.sleep(0.1)   # small pause so we don't spam the API

# --- Step 3: Save as JSON file ---

with open("hackernews_trending.json", "w") as f:
    json.dump(posts, f, indent=4)   # indent=4 makes it human-readable

print(f"\n✅ Done! Saved {len(posts)} posts to hackernews_trending.json")

from google.colab import files
files.download("hackernews_trending.json")