# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_q6uA0Yonyn_4__vn6ECCaQSYu_LoXW
"""



# task1.py
# TrendPulse - Task 1
# Goal: Fetch top trending posts from HackerNews API and save as JSON

import requests   # to make web requests
import json       # to save data as JSON file
import time       # to add small delay between requests (good practice)

# --- Step 1: Fetch the list of top story IDs ---

print("Fetching top story IDs from HackerNews...")

ids_url = "https://hacker-news.firebaseio.com/v0/topstories.json"
response = requests.get(ids_url)

# Check if request worked
print("Status Code:", response.status_code)

top_ids = response.json()          # this gives a list of IDs like [1234, 5678, ...]
top_ids = top_ids[:25]             # we only want top 25 posts

print(f"Got {len(top_ids)} story IDs")

# --- Step 2: Fetch details for each story ---

print("Fetching details for each story...")

posts = []   # empty list to collect all post data

for story_id in top_ids:
    # Build URL for each individual story
    story_url = f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json"

    story_response = requests.get(story_url)
    story = story_response.json()   # get that story's data

    # Some stories might be missing fields, use .get() to avoid errors
    extracted = {
        "id":          story.get("id"),
        "title":       story.get("title"),
        "author":      story.get("by"),
        "score":       story.get("score"),
        "num_comments": story.get("descendants", 0),  # 0 if no comments
        "url":         story.get("url", "No URL"),
        "time":        story.get("time")               # Unix timestamp
    }

    posts.append(extracted)
    print(f"  ✅ Fetched: {story.get('title', 'No title')[:50]}")  # print first 50 chars

    time.sleep(0.1)   # small pause so we don't spam the API

# --- Step 3: Save as JSON file ---

with open("hackernews_trending.json", "w") as f:
    json.dump(posts, f, indent=4)   # indent=4 makes it human-readable

print(f"\n✅ Done! Saved {len(posts)} posts to hackernews_trending.json")

# task2.py
# TrendPulse - Task 2
# Goal: Load JSON from Task 1, clean it using Pandas, save as CSV

import pandas as pd   # pandas for data cleaning
import json           # to read the JSON file

# --- Step 1: Load the JSON file into a DataFrame ---

with open("hackernews_trending.json", "r") as f:
    data = json.load(f)   # loads JSON as a Python list

df = pd.DataFrame(data)   # converts list of dicts into a table

print("=== Raw Data ===")
print(df)                 # see the full table
print("\nShape:", df.shape)  # (rows, columns)

# --- Step 2: Check for missing values ---

print("\n=== Missing Values ===")
print(df.isnull().sum())   # counts missing values per column

# Fill missing values
df['url'] = df['url'].fillna('No URL')          # if url is missing, fill with 'No URL'
df['author'] = df['author'].fillna('Unknown')   # if author missing, fill with 'Unknown'
df['score'] = df['score'].fillna(0)             # if score missing, fill with 0
df['num_comments'] = df['num_comments'].fillna(0)

# --- Step 3: Remove duplicate rows ---

print("\nDuplicates before:", df.duplicated().sum())
df = df.drop_duplicates()   # removes any repeated rows
print("Duplicates after:", df.duplicated().sum())

# --- Step 4: Convert Unix timestamp to readable date ---

# 'time' column has numbers like 1743600000 (seconds since 1970)
# We convert it to something like "2026-04-01 10:30:00"

df['time'] = pd.to_datetime(df['time'], unit='s')
print("\nSample date after conversion:", df['time'][0])

# --- Step 5: Remove posts with score = 0 ---

print("\nRows before score filter:", len(df))
df = df[df['score'] > 0]   # keep only rows where score is more than 0
print("Rows after score filter:", len(df))

# --- Step 6: Reset index ---

df = df.reset_index(drop=True)   # resets row numbers to 0,1,2,3...

# --- Step 7: Final check and save as CSV ---

print("\n=== Cleaned Data ===")
print(df.head())              # shows first 5 rows
print("\nData types:")
print(df.dtypes)              # shows type of each column

df.to_csv("hackernews_clean.csv", index=False)   # save, index=False means don't save row numbers

print("\n✅ Saved cleaned data to hackernews_clean.csv")

from google.colab import files
files.download("hackernews_clean.csv")